# Numpy

In [2]:
import numpy as np

# Help Recieved: 
# np library sheet: http://datacamp-community-prod.s3.amazonaws.com/ba1fe95a-8b70-4d2f-95b0-bc954e9071b0
# I googled how to do a reversed for loop

### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint:** You can also use **np.identity()** function ]

In [5]:
m = np.eye(10)

print(m)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.array()** function

In [39]:
a = np.array([])

for x in reversed(range(1, 10)):
    a = np.append(a, x)
    
a.resize(3, 3)
print(a)

[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


### Question 3

Interchange both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [40]:
t = a.transpose()

print(t)

[[9. 6. 3.]
 [8. 5. 2.]
 [7. 4. 1.]]


### Question 4
Add + 1 to all the elements in the given matrix.

In [42]:
add = np.add(t, 1)

print(add)

[[10.  7.  4.]
 [ 9.  6.  3.]
 [ 8.  5.  2.]]


### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function

In [47]:
nd6 = [[1, 4, 9, 121, 144, 169],
 [ 16, 25, 36, 196, 225, 256],
 [ 49, 64, 81, 289, 324, 361]]

print(nd6)

m = np.mean(nd6)

print(m)

[[1, 4, 9, 121, 144, 169], [16, 25, 36, 196, 225, 256], [49, 64, 81, 289, 324, 361]]
131.66666666666666


### Question 6

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [52]:
print(t)

t2 = t

print(t2)

d = np.dot(t, t2)

print(d)

[[9. 6. 3.]
 [8. 5. 2.]
 [7. 4. 1.]]
[[9. 6. 3.]
 [8. 5. 2.]
 [7. 4. 1.]]
[[150.  96.  42.]
 [126.  81.  36.]
 [102.  66.  30.]]


### Array Slicing/Indexing:

- Now we'll learn to access multiple elements or a range of elements from an array.

### Question 7

Print the array elements from start to 4th position

In [56]:
a = np.array([])

for x in range(20):
    a = np.append(a, x)
    
print(a)

s = a[4: len(a)]

print(s)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


### Question 8

- Return elements from first position with step size 2. (Difference between consecutive elements is 2)

In [68]:
print(s)
print("-" * 100)

for x in range(0, len(s), 2):
    print(s[x])
    


[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
----------------------------------------------------------------------------------------------------
4.0
6.0
8.0
10.0
12.0
14.0
16.0
18.0
